/*
 * generated by Xtext
 */
package org.agileware.natural.cucumber.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.agileware.natural.cucumber.services.CucumberGrammarAccess;

public class CucumberParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CucumberGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.agileware.natural.cucumber.parser.antlr.internal.InternalCucumberParser createParser(XtextTokenStream stream) {
		return new org.agileware.natural.cucumber.parser.antlr.internal.InternalCucumberParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Feature";
	}
	
	public CucumberGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CucumberGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
